### ISSUE TITLE
Find a Good JSON Parser and Parse Spotify API Responses

### ISSUE THREAD

**Issue by levymitchell0** [levymitchell0/SpotifyInsights#6]
Depends upon #1.

**Comment by levymitchell0** [comment]
Good JSON parser https://github.com/stleary/JSON-java/.

**Comment by wang-4** [comment]
https://www.oracle.com/technical-resources/articles/java/json.html
I'm kinda confused if this is native to Java and/or if we need to find something else?

**Comment by wang-4** [comment]
https://github.com/ralfstx/minimal-json
Minimal, as the title suggests

**Comment by levymitchell0** [comment]
Closing because it looks like the `org.json` parser is the only one that's been found so far that's fully implemented and not stale.
